### ISSUE TITLE
模型应用问题

### ISSUE THREAD

**Issue by Niclouge** [paritybit-ai/XFL#43]
在纵向联合建模过程中，会有一个路径保存模型，因此存在两个疑问：
1、该模型是一部分模型还是一个完整的模型？
2、该模型是否支持联合预测？

**Comment by hwang-ustc** [comment]
纵向建模时每个参与方都只会保存完整模型中和自身相关的那一部分参数，在联合推断时需要所有参与方的模型参数来共同参与才可以进行预测。
